### ISSUE TITLE
word_dict_0.js code in ipython

### ISSUE THREAD

**Issue by naveed-hearst** [kazunori279/cloudml-demo#1]
Hi,

It would be nice to have the code to convert the result to word_dict_0.js file, not sure if i am missing anything. Also code for creating the segment table.

**Comment by kazunori279** [comment]
It's in the last of [this file](https://github.com/kazunori279/cloudml-demo/blob/master/Similarity%2Bsearch%2Bon%2BStack%2BOverflow.ipynb).
